name: sample_bloc_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  # hive no sql database
  hive: ^2.2.3
  # path
  path_provider: ^2.1.1
  # get it singleton
  get_it: ^7.6.4
  # async
  async: ^2.11.0
  # equatable
  equatable: ^2.0.5
  # state manager
  flutter_bloc: ^8.1.3
  # interceptor
  dio: ^5.3.3
  dio_retry_plus: ^2.0.3
  retrofit: ^4.0.1
  # internet check
  internet_connection_checker: ^1.0.0+1
  # chuck
  chuck_interceptor: ^2.0.5
  # box
  gap: ^3.0.1
  # pin put
  pinput: ^3.0.1
  # svg render
  flutter_svg: ^2.0.7
  # dropdown
  dropdown_button2: ^2.3.9
  # cached image
  cached_network_image: ^3.3.0
  # native splash
  flutter_native_splash: ^2.3.3
  # firebase
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  firebase_messaging: ^14.6.9
  firebase_crashlytics: ^3.3.7
  firebase_performance: ^0.9.2+7
  # local notification
  flutter_local_notifications: ^16.1.0
  # router
  go_router: ^11.1.4
  google_fonts: ^6.1.0
  yandex_mapkit: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  bloc_test: ^9.1.4
  retrofit_generator: ^7.0.8

flutter:

  uses-material-design: true

  assets:
    - assets/locale/
    - assets/fonts/
    - assets/svg_picture/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
